[tools]
bun = "1"

[tasks.deploy]
description = "Deploy the project to Cloudflare Workers"
run = [
  "bun run cf:typegen",
  "bunx tsc --noEmit",
  "bun run db:generate",
  "bun run db:migrate --remote",
  "bun run deploy"
]
